volumes:
  rust_data:
services:
  rust:
    # Limiting server resources
    cpu_count: 16
    mem_limit: 8gb
    init: true
    user: root
    build: .
    env_file:
      - path: .env
        required: false
    # Do not change this from restart: always. Maintenance scripts assume
    # docker-compose auto restarts the rust server.
    restart: always
    volumes:
      - ./data:/home/steam
      - ./mod-configs/:/home/steam/serverfiles/oxide/config/:rw
      - ./custom-mods/:/custom-plugins/:ro
      - ./custom-maps/:/custom-maps/:rw
      - ./harmony-mods:/home/steam/serverfiles/HarmonyMods
      - ./harmony-config:/home/steam/serverfiles/HarmonyConfig
      - ./utils/:/utils/:ro
    ports:
      - ${RUST_RCON_INTERFACE:-127.0.0.1}:28016:28016
      - 0.0.0.0:28015:28015/udp
      - 0.0.0.0:8000:8000/tcp
    healthcheck:
      test: ["CMD", "pgrep", "RustDedicated"]
      interval: 10s
      retries: 3
      start_period: 15m
#    devices:
#      - /dev/dri:/dev/dri
